# Basic Site Settings
locale                   : "en-US"
title                    : "Welcome to my page!"
title_separator          : "-"
name                     : &name "Di Fang"
description              : &description "personal description"
url                      : https://fangdi2009.github.io/mypage # Base URL
baseurl                  : "" 
repository               : "https://fangdi2009.github.io/mypage"

# Site Author Settings
author:
  avatar           : "profile.jpg"
  name             : "Di Fang, PhD"
  location         : "Gainesville"
  employer         : "University of Florida"
  uri              : https://fred.ifas.ufl.edu/about/directory/di-fang/
  email            : "difang@ufl.edu"
  googlescholar    : "https://scholar.google.com/citations?user=Qq5DoMsAAAAJ&hl=en"
  github           : "academicpages"

# Navigation settings (header links to markdown files)
header_pages:
  - index.md        # Home page
  - teaching.md     # Teaching page
  - publications.md # Publications page
  - cv.md           # CV page

# Markdown collections (for linking markdown files)
collections:
  teaching:
    output: true
    permalink: /teaching/

  publications:
    output: true
    permalink: /publications/

  cv:
    output: true
    permalink: /cv/

# Other settings (you can retain or update as per your need)
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
